apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fkmq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-vqro-tenant/byoc-app-rgrz/fkmq@sha256:ed22c6acd9d4b33478180e221926b76aad9b7530ec7a61b3cce4126cfd30c084
        name: my-java-quarkus
        resources: {}
status: {}
